version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./data/line.sqlite/
    ports:
      - "3306:3306"
    restart: always